apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: metal-pod-reaper
  labels:
    name: metal-pod-reaper
spec:
  selector:
    matchLabels:
      name: metal-pod-reaper
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: metal-pod-reaper
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
      # We have to be able to ping nodes directly on the host network
      hostNetwork: true
      serviceAccountName: metal-pod-reaper
      containers:
      - name: mpodr
        image: quay.io/appvia/mpodr:v0.1.0
        env:
        - name: DRY_RUN
          # test this first!
          value: "true"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
